######################################################################
# Automatically generated by qmake (1.07a) Mon Sep 3 18:09:16 2007
######################################################################

TEMPLATE = app
CONFIG -= moc
INCLUDEPATH += .

# Input
SOURCES += accum.c \
           gl_widget.cpp \
           gui.cpp \
           main.cpp \
           md3_parse.c \
           quaternion.c \
           render.c \
           tga.c \
           util.c \
           world.c
